name       : compizconfig-python
version    : 0.8.16
release    : 1
source     :
    - https://gitlab.com/compiz/compizconfig-python/-/archive/v0.8.16/compizconfig-python-v0.8.16.tar.bz2 : 18d1271b33cc9b64c38670aa20eea531f702c2010fc5a018475cb0c9ff751382
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Python bindings for libraries/plugins for compizconfig-settings.
description: |
    Python bindings for libraries/plugins for compizconfig-settings.
builddeps  :
    - pkgconfig(libcompizconfig)
    - pkgconfig(python-3.6)
    - cython
setup      : |
    sed -i "s|2.7|3.0|g" configure.ac
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
